# Generated by Django 5.2.3 on 2025-06-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kanban_app", "0003_task_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("to-do", "To Do"),
                    ("in-progress", "In Progress"),
                    ("review", "Review"),
                    ("done", "Done"),
                ],
                default="todo",
                max_length=30,
            ),
        ),
    ]
