# Generated by Django 5.2.3 on 2025-09-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kanban_app", "0008_graphicsrapport"),
    ]

    operations = [
        migrations.CreateModel(
            name="KVStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=150, unique=True)),
                ("value", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
