# Generated by Django 5.2.3 on 2026-07-19 18:14

import django.db.models.deletion
import kanban_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0010_alter_kvstore_key_alter_kvstore_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booklet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('strategic-assortment', 'Strategic Assortment')], default='strategic-assortment', max_length=50)),
                ('period', models.CharField(help_text='Edition month in YYYY-MM format.', max_length=7)),
                ('file', models.FileField(upload_to=kanban_app.models.booklet_upload_path)),
                ('file_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(default='text/html', max_length=100)),
                ('size', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booklets', to='kanban_app.board')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_booklets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-period', '-updated_at'),
                'constraints': [models.UniqueConstraint(fields=('board', 'document_type', 'period'), name='unique_booklet_edition_per_board')],
            },
        ),
    ]
