# Generated by Django 5.2.3 on 2026-07-21

import django.db.models.deletion

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "kanban_app",
            "migration-0012-board-document",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardToolStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "market",
                    models.CharField(
                        choices=[
                            ("CH", "Switzerland"),
                            ("AT", "Austria"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("booklet", "Booklet"),
                            ("review-model", "Review Model"),
                            (
                                "tracking-dashboard",
                                "Tracking Dashboard",
                            ),
                            ("online", "Online"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "weekly_status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in-progress", "In progress"),
                            ("done", "Done"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "last_data_update",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "reference_date_flags",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "price",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "sales_date",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "sku_view_units",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_statuses",
                        to="kanban_app.board",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_tool_statuses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("market", "document_type"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("board", "market", "document_type"),
                        name="unique_board_tool_status",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(market__in=("CH", "AT")),
                        name="bts_market_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            document_type__in=(
                                "booklet",
                                "review-model",
                                "tracking-dashboard",
                                "online",
                            )
                        ),
                        name="bts_document_type_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            weekly_status__in=(
                                "open",
                                "in-progress",
                                "done",
                            )
                        ),
                        name="bts_weekly_status_valid",
                    ),
                ],
            },
        ),
    ]