# Generated by Django 5.2.3 on 2026-07-19

import django.db.models.deletion
import kanban_app.models

from django.conf import settings
from django.db import migrations, models


def normalize_document_types(apps, schema_editor):
    """Map the legacy booklet type to the generic document type."""
    BoardDocument = apps.get_model(
        "kanban_app",
        "BoardDocument",
    )

    BoardDocument.objects.filter(
        document_type="strategic-assortment",
    ).update(
        document_type="booklet",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("kanban_app", "0011_booklet"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="booklet",
            name="unique_booklet_edition_per_board",
        ),
        migrations.RenameModel(
            old_name="Booklet",
            new_name="BoardDocument",
        ),
        migrations.AddField(
            model_name="boarddocument",
            name="market",
            field=models.CharField(
                choices=[
                    ("CH", "Switzerland"),
                    ("AT", "Austria"),
                ],
                default="CH",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="boarddocument",
            name="sales_date",
            field=models.DateField(
                help_text=(
                    "Data status represented by this edition. "
                    "Null is reserved for documents migrated "
                    "from the legacy archive."
                ),
                null=True,
            ),
        ),
        migrations.RunPython(
            normalize_document_types,
        ),
        migrations.AlterField(
            model_name="boarddocument",
            name="board",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="kanban_app.board",
            ),
        ),
        migrations.AlterField(
            model_name="boarddocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("booklet", "Booklet"),
                    ("review-model", "Review Model"),
                    (
                        "tracking-dashboard",
                        "Tracking Dashboard",
                    ),
                    ("online", "Online"),
                ],
                default="booklet",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="boarddocument",
            name="file",
            field=models.FileField(
                upload_to=(
                    kanban_app.models
                    .board_document_upload_path
                ),
            ),
        ),
        migrations.AlterField(
            model_name="boarddocument",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="uploaded_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="boarddocument",
            constraint=models.UniqueConstraint(
                fields=(
                    "board",
                    "market",
                    "document_type",
                    "period",
                ),
                name="unique_board_document_edition",
            ),
        ),
    ]