# Generated by Django 5.2.3 on 2025-06-15 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kanban_app", "0004_alter_task_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the board was created."
            ),
        ),
        migrations.AlterField(
            model_name="board",
            name="members",
            field=models.ManyToManyField(
                help_text="Users who are members of this board.",
                related_name="boards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="board",
            name="owner",
            field=models.ForeignKey(
                help_text="The user who owns this board.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_boards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="board",
            name="title",
            field=models.CharField(
                help_text="The title of the board (max. 100 characters).",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                help_text="User who wrote the comment.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the comment was created."
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="task",
            field=models.ForeignKey(
                help_text="Task to which this comment belongs.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="kanban_app.task",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(help_text="Content of the comment."),
        ),
        migrations.AlterField(
            model_name="task",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                help_text="User assigned to complete this task.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks_assigned",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="board",
            field=models.ForeignKey(
                help_text="Reference to the board this task belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="kanban_app.board",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the task was created."
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who created this task.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(
                blank=True, help_text="Optional: Description of the task."
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateField(
                blank=True, help_text="Optional: Due date for this task.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                help_text="Priority level of the task.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                help_text="User assigned to review this task.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks_reviewing",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("to-do", "To Do"),
                    ("in-progress", "In Progress"),
                    ("review", "Review"),
                    ("done", "Done"),
                ],
                default="to-do",
                help_text="Current status in the workflow.",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(
                help_text="Title of the task (max. 255 characters).", max_length=255
            ),
        ),
    ]
