# Generated by Django 5.2.3 on 2025-09-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kanban_app", "0009_kvstore"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kvstore",
            name="key",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="kvstore",
            name="value",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
